# Generated by Django 3.0.6 on 2020-07-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
